FROM node:23-alpine

WORKDIR /app

# Copy package.json and package-lock.json
COPY package*.json ./

# Install dependencies
RUN npm install

# Copy source code
COPY . .

# Generate Prisma client
RUN npm run prisma:dev

# Expose the port the app runs on
EXPOSE 3003

# Command to run the application in development mode with hot-reloading
CMD ["npm", "run", "dev"]
