-- AlterTable
ALTER TABLE `customer_detail` MODIFY `cd_consider` VARCHAR(191) NULL,
    MODIFY `cd_typeinout` VARCHAR(191) NULL,
    MODIFY `cd_custype` VARCHAR(191) NULL,
    MODIFY `cd_cusservice` VARCHAR(191) NULL,
    MODIFY `cd_channels` VARCHAR(191) NULL,
    MODIFY `cd_num` INTEGER NULL,
    MODIFY `cd_capital` VARCHAR(191) NULL,
    MODIFY `cd_emp` VARCHAR(191) NULL,
    MODIFY `cd_shareholders` VARCHAR(191) NULL,
    MODIFY `cd_num_saka` VARCHAR(191) NULL,
    MODIFY `cd_frequency` VARCHAR(191) NULL,
    MODIFY `cd_leader` VARCHAR(191) NULL,
    MODIFY `cd_priority` VARCHAR(191) NULL,
    MODIFY `cd_address` VARCHAR(191) NULL;
